### ISSUE TITLE
[Feature Request] Restructure Repo Structure

### ISSUE THREAD

**Issue by 1chooo** [kshitiz11101/The-DSA#1]
### Descriptions
Hi @kshitiz11101 , I am very grateful for this repository and find it very interesting. However, I would like to suggest organizing the code into specific folders based on their topic. If you agree with this suggestion, I would be happy to fork the repository and provide my assistance in organizing the code. 

### Example repo structure
```shell
PROJECT_ROOT
├── BinaryTree/
|    ├── BinaryTree.cpp
|    └── main.cpp
|     :
└──   :
```

Please feel free to DM me.

BR, @1chooo

**Comment by kshitiz11101** [comment]
Hello ,@1chooo. I want to thank you for loving this repository. Of course, I also wish to group my solutions into folders by subject. However, you can fork this repository and organise the files in the appropriate directories according to their topics if you so choose. Additionally, it would be wonderful if you also documented these events. Thank You:)

**Comment by 1chooo** [comment]
Hey @kshitiz11101.
Certainly, I will document the steps and events that I have completed so that you can easily track and merge them in the future.

Cheers,
@1chooo

**Comment by kshitiz11101** [comment]
That's great:)
